version: '3.4'

services:

    keycloak:
        image: jboss/keycloak:latest
        container_name: keycloak
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin            
            - KEYCLOAK_IMPORT=/tmp/keycloak-config-import.json
        ports:
            - "8080:8080"
            - "8443:8443"
        volumes:          
          - ./keycloak-config-import.json:/tmp/keycloak-config-import.json      
        networks:
            - keycloak-network
                        
networks:
    keycloak-network:
        driver: bridge